# Generated by Django 5.0.7 on 2025-01-18 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepteddoner',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.event'),
        ),
    ]
