# Generated by Django 5.0.7 on 2025-02-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_event_doner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
